---
title: "Untitled"
output: html_document
---

```{r}
library(tidyverse)
library(amstools)
library(DBI)
```

Create a database connection, and a dbplyr connection to mass_spec

```{r}
con <- conNOSAMS()
mass_spec <- tbl(con, "mass_spec")
```

Check the data

```{r}
mass_spec %>% 
  filter(ms_date > "2020-01-01") %>% 
  head()
```

Having trouble finding standards by rec_num. Maybe a problem with the join to create mass_spec?

```{r}
mass_spec %>% 
  group_by(rec_num) %>%
  filter(n() > 1000) %>% 
  summarize("d13C mean" = mean(c13_cr_3std),
            "d13C sd" = sd(c13_cr_3std),
            N = n())
  
```

Look at histogram of beam size

```{r}
mass_spec %>% 
  filter(beam_size > 0,
         beam_size < 0.001) %>%
  ggplot(aes(beam_size)) + geom_histogram()
```

Plot INST3 GAS

```{r}
mass_spec %>% 
  filter(beam_size > 0,
         beam_size < 0.001,
         sample_desc == "INST3 GAS",
         c13_cr_3std < 0) %>%
  ggplot(aes(beam_size, c13_cr_3std)) + 
           geom_point()
```

Check NBS-19

```{r}
mass_spec %>% 
  filter(beam_size > 0,
         beam_size < 0.001,
         sample_desc == "NBS-19",
         c13_cr_3std < 10) %>%
  ggplot(aes(beam_size, c13_cr_3std)) + 
           geom_point()
```
Check C-2

```{r}
mass_spec %>% 
  filter(beam_size > 0,
         beam_size < 0.001,
         rec_num == 1082,
         c13_cr_3std > -7.5) %>%
  ggplot(aes(beam_size, c13_cr_3std)) + 
           geom_point()
```